name: HACS Action

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "plugin"